[workspace]
resolver = "2"

members = [
    "alg-list-gen",
    "alg-trainer",
    "bld-solver",
    "cube",
    "cycles",
    "kociemba",
    "random-state",
]

[workspace.dependencies]
rand = { version = "0.8", default-features = false }
